export const SHOW_CATEGORY = 'SHOW_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
